
List<String> getCategoryList() {
  return [
    "Action and Adventure",
    "Alternate history",
    "Anthology",
    "Art/Architecture",
    "Autobiography",
    "Biography",
    "Business/Economics",
    "Chick lit",
    "Children",
    "Classic",
    "Comic",
    "Coming-of-age"
    "Cookbook",
    "Craft/Hobbies",
    "Crime",
    "Diary",
    "Dictionary",
    "Drama",
    "Encyclopedia",
    "Fairytale",
    "Fantasy",
    "Guide",
    "Graphic novel",
    "Health/Fitness",
    "History",
    "Historical fiction",
    "Home and garden",
    "Horror",
    "Humor",
    "Journal",
    "Math",
    "Memoir",
    "Mystery",
    "Paranormal romance",
    "Philosophy",
    "Picture book",
    "Poetry",
    "Political thriller",
    "Prayer",
    "Religion, spirituality, and new age",
    "Romance",
    "Satire",
    "Science",
    "Science fiction",
    "Self help",
    "Short story",
    "Sports and leisure",
    "Suspense",
    "Textbook",
    "Thriller",
    "Travel",
    "True crime",
    "Western",
    "Young adult"
  ];
}